### ISSUE TITLE
GetImplementationInDomain throws exceptions

### ISSUE THREAD

**Issue by krauthaufen** [Ultz/SuperTools#2]
Hey, 

I've been using your GLFW/OpenGL bindings for quite some time now and totally like  them.
However I stumbled upon a problem when loading APIs in *unconventional*  environments (e.g. tests).

The Problem boils down to [this](https://github.com/Ultz/SuperTools/blob/7fd9d8e72332208eaf0717dc282542f76e2df142/src/Ultz.SuperInvoke/LibraryActivator.cs#L46) line here, where `.GetTypes` raises exceptions like 

```
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.IntelliTrace.Core, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'
```

I honestly don't fully understand why this happens (loaded Assemblys should be complete???) but we had a similar problem in one of our projects  and *resolved* it via adding `try { .. } catch` around it.

**Comment by Perksey** [comment]
Will fix this now.

**Comment by krauthaufen** [comment]
That was quick^^

**Comment by krauthaufen** [comment]
Thanks! Solved my issue!!

**Comment by Perksey** [comment]
No problem, be sure to update to Silk.NET 1.0.1 as well to get the latest bug fixes (this also updates the SuperInvoke version to include this bugfix)
